server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          url: http://localhost:8081/
          predicates:
            - Path=/first-service/**
        - id: second-service
          url: http://localhost:8082/
          predicates:
            - Path=/second-service/**
