server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false # EurekaConfigBean?? eureka service? ??? ???? ???? ?? (Service Discovery? ??? ?? ??)
    fetch-registry: false # ?????? ??? ???? ??? ????? ??? ???? ??? ??? ???.
